// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package rewardsonline.accounts;

import org.springframework.beans.factory.annotation.Configurable;
import rewardsonline.accounts.AccountIntegrationTest;

privileged aspect AccountIntegrationTest_Roo_Configurable {
    
    declare @type: AccountIntegrationTest: @Configurable;
    
}
