/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: VMware vFabric tc Runtime 2.7.0.RELEASE/7.0.27.A.RELEASE
 * Generated at: 2012-11-09 09:35:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.catalina.util.ServerInfo;;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE HTML>\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"http://www.springsource.com/sites/all/themes/zen/springsource2/favicon.ico\" type=\"image/x-icon\">\n");
      out.write("\t<title>VMware vFabric tc Server &#8212; Developer Edition with Spring Insight</title>\n");
      out.write("\t<link type=\"text/css\" rel=\"stylesheet\" href=\"splash.css\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t<div id=\"container\">\n");
      out.write("\n");
      out.write("\t\t<!-- Header -->\n");
      out.write("\t\t<div id=\"hdr\"><span class=\"utility\"><a href=\"http://www.vmware.com/products/vfabric/\" title=\"VMware vFabric, Cloud Application Platform\">VMware vFabric, Cloud Application Platform</a></span><a href=\"http://www.vmware.com/\" title=\"VMware\"><h1>VMware</h1></a></div>\n");
      out.write("\t\t<div class=\"clearfix\"></div>\n");
      out.write("\n");
      out.write("\t\t<!-- Body -->\n");
      out.write("\t\t<div id=\"content\">\n");
      out.write("\t\t\t<div id=\"intro\">\n");
      out.write("\t\t\t\t<h4>VMware vFabric</h4>\n");
      out.write("\t\t\t\t<h2>tc Server &#8212; Developer Edition with Spring Insight</h2>\n");
      out.write("\t\t\t\t<h3 class=\"title\">Congratulations! You have successfully setup and started vFabric tc Server Developer Edition.  You are ready to go!</h3>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"bodyrule\"><hr /></div>\n");
      out.write("\n");
      out.write("\t\t\t<div id=\"toc\">\n");
      out.write("\t\t\t\t<!-- Table of Contents -->\n");
      out.write("\t\t\t\t<h4 class=\"modHdr\">vFabric tc Server Developer Edition Online</h4>\n");
      out.write("\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t<li><a href=\"http://www.springsource.com/developer/tcserver\">Home</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"http://www.vmware.com/support/pubs/vfabric-tcserver.html\">Documentation</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"http://forum.springsource.org/forumdisplay.php?f=71\">Discussion</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"https://issuetracker.springsource.com/browse/INSIGHT\">Issues</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"http://www.springsource.com/developer/sts\">SpringSource Tool Suite (STS)</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<h3>More information can be found at:</h3>\n");
      out.write("\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t<a href=\"http://www.springsource.com/products/tcserver/devedition\">vFabric tc Server Developer Edition Homepage</a><br />The official home for the Developer Edition and Spring Insight.\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"http://www.vmware.com/support/pubs/vfabric-tcserver.html\">vFabric tc Server Documentation</a><br />Find out what it does, how to use it, and other useful information.</li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"http://forum.springsource.org/forumdisplay.php?f=71\">vFabric tc Server Discussion Forum</a><br />Tell us what you think, start a conversation with other users and discuss application performance.</li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"https://issuetracker.springsource.com/browse/INSIGHT\">vFabric tc Server Issues &amp; Improvements (Jira)</a><br />Found a problem or a bug? Got an idea about how to make Spring Insight better? Open a ticket in JIRA and let us know about it.</li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"http://www.springsource.com/products/sts\">SpringSource Tool Suite (STS)</a><br />Go here to download the latest STS release with Spring Insight bundled in!</li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li><a href=\"http://www.vmware.com/products/vfabric-tcserver/\">vFabric tc Server Standard Edition Homepage</a><br />The official home for vFabric tc Server Standard Edition.</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"clearfix\"></div>\n");
      out.write("\t\t<div id=\"versions\">\n");
      out.write("\t\t\tVMware vFabric tc Server Developer Edition 2.7.0.RELEASE<br/>\n");
      out.write("\t\t\t");
 out.println(ServerInfo.getServerInfo()); 
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div id=\"ftr\">&copy; 2011 VMware, Inc. All rights reserved.</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
